### ISSUE TITLE
Inserts hyphen into auto-generated room name - not accepted

### ISSUE THREAD

**Issue by flantel** [RocketChat/Apps.Jitsi#1]
Jitsi does not appear to allow anything but alpha-numeric room names. Auto-generated rooms names contain a "-" and therefore do not work.

**Comment by ChristineBoersen** [comment]
It doesn't look like you are open for pull requests, You just need to change this one line of code in slashcommand.ts, line 24 to not concatenation of the "-" between the roomName/id and the getSender().id.

`
const url = server + (roomName ? roomName : context.getRoom().id + context.getSender().id);
`

**Comment by sampaiodiego** [comment]
fixed by #2
