### ISSUE TITLE
Jitsi missing configuration

### ISSUE THREAD

**Issue by le0np** [RocketChat/Apps.Jitsi#34]
Hello, 

Two nights ago, some kind of update happened as it seems and it messed up Jitsi configuration. 
We managed to enable it again, but the strange thing is that it was missing from Marketplace and needed to be enabled again. After it was enabled in Marketplace, the Community version was active and needed to be synced again to go back to the Starter version.  The only thing about what happened I was able to find in the Docker log but it is not very clear to me:

`{"t":{"$date":"2024-05-22T04:00:23.790+00:00"},"s":"I",  "c":"COMMAND",  "id":51803,   "ctx":"conn37","msg":"Slow query","attr":{"type":"command","ns":"meteor.$cmd","command":{"update":"rocketchat_apps","updates":[{"q":{"id":"3b387ba9-f57c-44c6-9810-8c0256abd64c"},"u":{"$set":{"_id":"655dfc190ca1277588754aae","id":"3b387ba9-f57c-44c6-9810-8c0256abd64c","info":{"id":"3b387ba9-f57c-44c6-9810-8c0256abd64c","version":"2.0.6","requiredApiVersion":"^1.33.0","iconFile":"icon.png","author":{"name":"Rocket.Chat Technologies Corp.","homepage":["https://github.com/RocketChat/Rocket.Chat"](https://github.com/RocketChat/Rocket.Chat),"support":["https://github.com/RocketChat/Rocket.Chat"](https://github.com/RocketChat/Rocket.Chat)},"name":"Jitsi","nameSlug":"jitsi","classFile":"src/JitsiApp.js","description":"Jitsi Conference Calls Provider","implements":[]}}}}]},"numYields":0,"reslen":245,"locks":{"ParallelBatchWriterMode":{"acquireCount":{"r":1}},"FeatureCompatibilityVersion":{"acquireCount":{"r":1,"w":1}},"ReplicationStateTransition":{"acquireCount":{"w":2}},"Global":{"acquireCount":{"r":1,"w":1}},"Database":{"acquireCount":{"w":1}},"Collection":{"acquireCount":{"w":1}},"Mutex":{"acquireCount":{"r":1}}},"flowControl":{"acquireCount":1,"timeAcquiringMicros":3},"readConcern":{"level":"local","provenance":"implicitDefault"},"writeConcern":{"w":"majority","wtimeout":0,"provenance":"implicitDefault"},"storage":{"data":{"bytesRead":37053,"timeReadingMicros":469}},"remote":"172.20.0.2:60796","protocol":"op_msg","durationMillis":123},"truncated":{"command":{"updates":{"0":{"u":{"$set":{"info":{"iconFileContent":{"type":"string","size":9951}}}}}}}},"size":{"command":37037}}`

I was also checking 3b387ba9-f57c-44c6-9810-8c0256abd64c file, but it looks like there is no complete info. 
Also, I was not able to find anything about the update online and was just wondering if you can point me in the right direction or if you know something. 

Thanks 

**Server Setup Information**
Version of Rocket.Chat Server: 6.6.0
Operating System: CentOS Stream 8
Deployment Method: Docker
Number of Running Instances: 1
MongoDB Version: 5.0
Proxy: Nginx
Firewalls involved: firewalld

**Comment by umamiMike** [comment]
Same hear.  It was functioning, now, there is an option for setting jitsi as the conference call app, but no config is available for it.

**Comment by le0np** [comment]
Hello @umamiMike, we figured out that the Jitsi app was disabled from the marketplace after this update. We enabled it back and then under conference call, we could again select Jitsi.
