### ISSUE TITLE
jwt authentication dosn't work 

### ISSUE THREAD

**Issue by cristiantod** [RocketChat/Apps.Jitsi#5]
With the slash jitsi app installed and jwt authentication enabled, the user who started the conference cannot join.

**Comment by graywolf336** [comment]
Sadly, we can not implement this yet in the App due to a limitation of the Apps Engine. Creating a signed payload requires an external package, from npm, to do it and a limit of the current version of the Apps Engine (as of the date of this comment) is that we can't use npm packages inside of an App.

**Comment by putt1ck** [comment]
is there an open issue for the Apps Engine on this? I'm guessing it would be a similar problem for scheduling meetings using a secured RocketChat/Jitsi Meet setup

**Comment by graywolf336** [comment]
Yes sir, there's an issue about this and also we have started planning what would be required to get it to work.

**Comment by putt1ck** [comment]
Is this the issue to track: https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/56 ? Is there anything we can do to move it along? We think it would be really neat for our Rocket/Jitsi integration work with Nextcloud.

**Comment by Fobhep** [comment]
are there any news regarding this?

**Comment by paulausz** [comment]
May there be a chance to configure a hard-coded access token that is automatically appended to every room link that is created? It would not make use of the proper token generation, but at least people could use your app together with the jwt authentification. For my use case, this would make sense as we are using the jwt authentification mainly to prevent random people to create and access rooms in our public jitsi instance, but we can trust our Rocket.Chat users.

**Comment by paulausz** [comment]
I created a sample app that has a menu that allows adding a fixed JWT token when creating a link (and some more options). 
![AppSettingsJWT](https://user-images.githubusercontent.com/76944204/104707445-b1493d80-571c-11eb-8dbb-06340d66c99d.PNG)
![JWT1](https://user-images.githubusercontent.com/76944204/104707496-c0c88680-571c-11eb-88b1-c79e91900c47.PNG)

I would be more than happy to create a pull request to add this feature to the app. Unfortunately, I still cannot deploy the original app to my test system to test the merged code (see #9)

**Comment by paulausz** [comment]
@graywolf336 would you be interested in a pull request to add a menu as seen above?

**Comment by graywolf336** [comment]
Yes sir, that would be fantastic! @paulausz

**Comment by Fafenback** [comment]
Hi ! Any chance to see this enhancement merged to master ?

**Comment by himpierre** [comment]
As of https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/56 it should be possible to continue, no?

**Comment by graywolf336** [comment]
@himpierre it is possible. We would accept a PR adding it, pending the dependency doesn’t have a while host of other dependencies so we don’t bloat the App Package.
