### ISSUE TITLE
Jitsi Meet integration app breaks links when user being called has punctuation in their username

### ISSUE THREAD

**Issue by christefano** [RocketChat/Apps.Jitsi#6]
When testing this Jitsi Meet integration app I tried calling the rocket.cat bot (this test instance doesn’t have any other accounts yet), and I discovered an unusual edge case that breaks the expected functionality.

It seems the Jitsi Meet integration app is unaware of Jitsi's URL requirements not to use punctuation in the URL. For example, this URL has a “.cat” at the end (presumably inherited from the rocket.cat bot’s username) and results in a 404 on the Jitsi Meet web UI:

https://meet.example.com/FYJpKZKmGcSqNr6zSdWPhvJpbfSnW6FXGmrocket.cat

**Comment by graywolf336** [comment]
@christefano we just published v1.0.0 of the App to the Marketplace! 🎉 

If you don't mind, can you update and see if this is still an issue?

**Comment by christefano** [comment]
Updated to 1.0.0, and the URL still has punctuation in it. I tried restarting Rocket.Chat just in case, and the issue persists.

Punctuation is still being included in the URL. (I was delighted, however, to find that the hostname setting is found under the App config! The `/jitsi` command is now working for me.)

**Comment by graywolf336** [comment]
Sounds like your instance didn't update correctly then. That setting was actually removed with v1.0.0 and the url has all punctuation removed. 🤔

**Comment by christefano** [comment]
Strange. The Apps -> Jitsi Slash Command page shows that I have version 1.0.0.

<img width="500" alt="Screen Shot 2020-05-22 at 10 13 25 AM" src="https://user-images.githubusercontent.com/105058/82692656-f8764180-9c14-11ea-8247-b57d2715d541.png">

I think this issue was closed too prematurely.

**Comment by graywolf336** [comment]
Can you replicate it on the Open server? As I tested it and even forcing a room name with it is valid:

<img width="641" alt="Screen Shot 2020-05-22 at 12 41 15 PM" src="https://user-images.githubusercontent.com/850391/82694802-8a884500-9c29-11ea-81b0-d31fe922e032.png">

**Comment by christefano** [comment]
Thanks for the suggestion. `/jitsi`  works for me on the open server.

It’s unclear why my version 1.0.0 app on my server hasn’t updated properly.

**Comment by graywolf336** [comment]
What version of Rocket.Chat are you running?

@d-gubert any idea why an App isn't updating even though it says it is up to date?

**Comment by christefano** [comment]
3.2.2 snap install on Ubuntu 18.04.
