### ISSUE TITLE
Deployment error: createRequire is not a function

### ISSUE THREAD

**Issue by paulausz** [RocketChat/Apps.Jitsi#9]
Hi there, 

I was trying to deploy your app to a fresh instance of Rocket.Chat using the rc-app deploy command. 
`rc-apps deploy --url http://localhost:3000 --username myuser --password mypass`

When I do so, the following output is produced:

>  Starting App Deployment to Server
   Getting Server Info... ✓
   Packaging the app... ✖
 ›   Error:    ⟿  createRequire is not a function

Do you know how to fix it? 

I enabled the development mode as suggested here: https://docs.rocket.chat/apps-development/getting-started/creating-an-example-app 

Node version 

> v10.19.0

Rc-apps version
> @rocket.chat/apps-cli/1.8.0 linux-x64 node-v10.19.0

Rocket.Chat (installed via snap)
 > 3.9.3 (1.21.0-alpha.4235)

Regards,
Paul

**Comment by graywolf336** [comment]
What version of Rocket.Chat?

**Comment by paulausz** [comment]
Looks like I forgot about the most important information: 

Rocket.Chat (installed via snap)
> 3.9.3 (1.21.0-alpha.4235)

**Comment by graywolf336** [comment]
@d-gubert what version of Rocket.Chat did we switch over to using compiled apps?

**Comment by d-gubert** [comment]
It was on 3.8

**Comment by d-gubert** [comment]
Wait, looking a bit more to the message, it looks like the error happens during the packaging, it hasn't even made it to Rocket.Chat yet... so weird.

@paulausz can you try to run the `rc-apps` command with node 12.x to test it? My guess is could be a version conflict we're not aware of

**Comment by paulausz** [comment]
I updated node and npm. 

> Node v12.20.1
npm 6.14.10

Then I received the following error:

> Starting App Deployment to Server
   Getting Server Info... ✓
   Packaging the app... ✖
 ›   Error:    ⟿  Cannot find module 'typescript'
 ›   Require stack:
 ›   - /home/paul/jitsicommand/Apps.Jitsi/app.json

So I installed typescript. 
`sudo npm install -g typescript`
`sudo npm link typescript`

Now I get

> Starting App Deployment to Server
   Getting Server Info... ✓
   Packaging the app... ✖
 ›   Error:    ⟿  Failed to resolve module: @rocket.chat/apps-engine/definition/accessors

**Comment by paulausz** [comment]
Based on my last comment, this is what I achieved yet:

Running 
`npm install`
Lead to 
> Starting App Deployment to Server
   Getting Server Info... ✓
[
  {
    file: undefined,
    start: undefined,
    length: undefined,
    messageText: "Cannot find type definition file for 'node'.",
    category: 1,
    code: 2688,
    reportsUnnecessary: undefined
  }
]
A VERY UNEXPECTED ERROR HAPPENED THAT SHOULD NOT!
   Packaging the app... ✖
 ›   Error:    ⟿  Language Service's Compiler Options Diagnostics contains 1 diagnostics.

Then running the following as suggested in here https://stackoverflow.com/questions/43542710/buildcannot-find-type-definition-file-for-node 
`npm install @types/node --save-dev`
Caused
> Starting App Deployment to Server
   Getting Server Info... ✓
   Packaging the app... ✖
 ›   Error:    ⟿  Error
 ›   /home/paul/jitsicommand/Apps.Jitsi/node_modules/@types/node/assert.d.ts (3,60): Cannot
 ›   find name 'asserts'.

Running the following as suggested in here: https://stackoverflow.com/questions/56595053/cannot-find-name-it-in-jest-typescript didn't change anything 
`npm install jest @types/jest ts-jest`

Also, just to check if I am able to upload an app at all, I uploaded the liftof-App (https://docs.rocket.chat/apps-development/getting-started/creating-an-example-app) . It worked.

**Comment by graywolf336** [comment]
@paulausz what's the difference between your sample app and this app? Yours works but this one doesn't. Any ideas? Is it the dependencies need updating?

**Comment by paulausz** [comment]
@graywolf336 that was a good hint. I modifyed the typescript version in in your package.json and now it works. 
This is the version I used. The min typescript version seems to be 3.0.0
>{
    "devDependencies": {
        "@rocket.chat/apps-engine": "^1.21.0",
        "@types/node": "^14.14.21",
        "tslint": "^5.11.0",
        **"typescript": "^4.1.3"**
    }
}

**To sum up what is needed to deploy the current app using rc-apps deploy**

1.  Clone the repo
` git clone https://github.com/RocketChat/Apps.Jitsi/`
2. Edit dependencies in package.json
>{
    "devDependencies": {
        "@rocket.chat/apps-engine": "^1.1.1",
        "tslint": "^5.11.0",
        "typescript": "^3.0.0"
    }
}
3. Run 
`npm install`
4. Run
`npm install @types/node --save-dev`
5. Deploy the app
`rc-apps deploy --url http://localhost:3000 --username "user" --password "password"`

**Comment by paulausz** [comment]
@graywolf336 If you like I can create a pull request to update the dependencies, but I don't have access yet.

**Comment by graywolf336** [comment]
Yes sir, if you can do that it would be great! You'll need to fork this repository to your account and then create a pull request from there to this one.

**Comment by Mariam613** [comment]
Packaging the app... ✓
   Getting Server Info... ✖
   ⟿  Error: Problems conecting to Rocket.Chat at http://localhost:3000 - please check the address
